name: Python Unittests Dashboard

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unittests (show each test result)
        env:
          PYTHONPATH: .
        run: |
          # -v  = verbose output (shows every test name and status)
          # no -b  (so print() stays buffered / hidden)
          python -m unittest discover -s test -p "test_*.py" -v

      - name: Notify on success
        if: success()
        run: echo "All unittests passed successfully!"

      - name: Notify on failure
        if: failure()
        run: echo "Some unittests failed. Check above for details."